server:
  port: 8081

spring:
  application:
    name: equipment-catalog   
  datasource:
    driverClassName: org.h2.Driver
    password: ''
    url: jdbc:h2:file:~/equipment;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    initialization-mode: always
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
     
eureka:
  instance: 
    hostname: localhost
    port: 9000
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
    server:
      wait-time-in-ms-when-sync-empty: 3000 
